### ISSUE TITLE
Data Flow doesn't send email or connect to server

### ISSUE THREAD

**Issue by klossteles** [dojot/docker-compose#55]
After installing  dojot, getting docker up (`docker-compose up -d`), creating a template and a device, i have followed this tutorial http://dojotdocs.readthedocs.io/pt_BR/latest/faq/faq.html) to create a data flow to send an email and another data flow to connect to my server, but when the device that i've created before receive some data information like temperature, no email is send and dojot doesn't connect to the server.
Using docker logs `sudo docker-compose logs --tail=0 --follow`,  i've got the following:
```javascript
iotagent-mqtt_1         | will handle authentication request undefined undefined mosqpub/18208-lucas
iotagent-mqtt_1         | ignoring internal message $SYS/Rbv8GIW/new/clients undefined
iotagent-mqtt_1         | will attempt to use client.id as id source
iotagent-mqtt_1         | will attempt to use topic as id source
iotagent-mqtt_1         | ignoring internal message $SYS/Rbv8GIW/disconnect/clients undefined
device-manager_1        | 172.18.0.21 - - [17/Apr/2018:12:46:44 +0000] "GET /device/312058 HTTP/1.1" 200 1417 "-" "axios/0.17.1"
iotagent-mqtt_1         | Published /admin/312058/attrs { current: 0,
iotagent-mqtt_1         |   temperature: 31.964783,
iotagent-mqtt_1         |   apparent_power: 16.590271,
iotagent-mqtt_1         |   power_factor: 0.946289,
iotagent-mqtt_1         |   voltage: 127.492249,
iotagent-mqtt_1         |   active_power: 15.699707,
iotagent-mqtt_1         |   power_frequency: 60.071228,
iotagent-mqtt_1         |   reactive_power: 0,
iotagent-mqtt_1         |   teste: 7 } mosqpub/18208-lucas undefined undefined
data-broker_1           | will publish event [admin] {"metadata":{"deviceid":"312058","tenant":"admin","timestamp":1523969204796,"templates":[1]},"attrs":{"current":0,"temperature":31.964783,"apparent_power":16.590271,"power_factor":0.946289,"voltage":127.492249,"active_power":15.699707,"power_frequency":60.071228,"reactive_power":0,"teste":7}}
flowbroker_1            | [ingestor] got new device event: { metadata: 
flowbroker_1            |    { deviceid: '312058',
flowbroker_1            |      tenant: 'admin',
flowbroker_1            |      timestamp: 1523969204796,
flowbroker_1            |      templates: [ 1 ] },
flowbroker_1            |   attrs: 
flowbroker_1            |    { current: 0,
flowbroker_1            |      temperature: 31.964783,
flowbroker_1            |      apparent_power: 16.590271,
flowbroker_1            |      power_factor: 0.946289,
flowbroker_1            |      voltage: 127.492249,
flowbroker_1            |      active_power: 15.699707,
flowbroker_1            |      power_frequency: 60.071228,
flowbroker_1            |      reactive_power: 0,
flowbroker_1            |      teste: 7 } }
flowbroker_1            | [executor] will handle node template
flowbroker_1            | [executor] hop (template) result: [{"payload":"This is the payload: [object Object] !"}]
data-broker_1           | will publish event [admin] {"metadata": {"deviceid": "312058", "tenant": "admin", "status": "online", "reason": "statusUpdate"}, "attrs": {"status": "online"}}
flowbroker_1            | [executor] will handle node template
flowbroker_1            | [executor] hop (template) result: [{"payload":{"current":0,"temperature":31.964783,"apparent_power":16.590271,"power_factor":0.946289,"voltage":127.492249,"active_power":15.699707,"power_frequency":60.071228,"reactive_power":0,"teste":7},"emailBody":"Your device generate this: [object Object] !"}]
flowbroker_1            | [ingestor] got new device event: { metadata: 
flowbroker_1            |    { deviceid: '312058',
flowbroker_1            |      tenant: 'admin',
flowbroker_1            |      status: 'online',
flowbroker_1            |      reason: 'statusUpdate' },
flowbroker_1            |   attrs: { status: 'online' } }
flowbroker_1            | [executor] will handle node http
flowbroker_1            | [executor] will handle node email
flowbroker_1            | [executor] will handle node template
flowbroker_1            | [executor] hop (template) result: [{"payload":{"status":"online"},"emailBody":"Your device generate this: [object Object] !"}]
flowbroker_1            | [executor] will handle node email
data-broker_1           | will publish event [admin] {"metadata": {"deviceid": "312058", "tenant": "admin", "status": "offline", "reason": "statusUpdate"}, "attrs": {"status": "offline"}}
flowbroker_1            | [ingestor] got new device event: { metadata: 
flowbroker_1            |    { deviceid: '312058',
flowbroker_1            |      tenant: 'admin',
flowbroker_1            |      status: 'offline',
flowbroker_1            |      reason: 'statusUpdate' },
flowbroker_1            |   attrs: { status: 'offline' } }
flowbroker_1            | [executor] will handle node template
flowbroker_1            | [executor] hop (template) result: [{"payload":{"status":"offline"},"emailBody":"Your device generate this: [object Object] !"}]
flowbroker_1            | [executor] will handle node email
iotagent-mqtt_1         | [iota] Cache cleanup done: 0 entries evicted
iotagent-mqtt_1         | [iota] Cache cleanup done: 0 entries evicted
```

From the log i can see that flowbroker is trying to handle the node email, but nothing happens after this (flowbroker doesn't log anything else).
There is another way to send the email or another way to get the log from flowbroker.

Thanks

**Comment by giovannicuriel** [comment]
Hi, @klossteles!

It's very likely that the issue you found was fixed by dojot/flowbroker#27. Could you, please, change the flowbroker image tag from 0.2.0 to 0.3.0-nightly20180416 in the docker-compose.yml file and try again? The flowbroker section would then be:

```
  flowbroker:
    image: dojot/flowbroker:0.3.0-nightly20180416
    restart: always
    depends_on:
      - rabbitmq
      - kafka
      - mongodb
      - auth
    networks:
      - default
      - flowbroker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:Z
```

And then you'll need to pull the new image and restart the service:
```
docker-compose pull flowbroker
docker-compose kill flowbroker
docker-compose up -d flowbroker
```
(Assuming all other services are already running. You may also need sudo for these commands)

This image contains a few other bugfixes since the release of 0.2.0 version.

**Comment by klossteles** [comment]
Hi, @giovannicuriel 
Thanks for the reply!
I've changed the flowbroker with the one you posted so it looked like this:
**Was:** 
```
  flowbroker:
    image: dojot/flowbroker:latest
    restart: always
    depends_on:
      - rabbitmq
      - kafka
      - mongodb
      - auth
    networks:
      - default
      - flowbroker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:Z
```

**Changed to:**
```
flowbroker:
    image: dojot/flowbroker:0.3.0-nightly20180416
    restart: always
    depends_on:
      - rabbitmq
      - kafka
      - mongodb
      - auth
    networks:
      - default
      - flowbroker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:Z
```
After running `docker-compose pull flowbroker` and  got
```
Pulling flowbroker (dojot/flowbroker:0.3.0-nightly20180416)...
	0.3.0-nightly20180416: Pulling from dojot/flowbroker
	f2b6b4884fc8: Already exists
	4fb899b4df21: Already exists
	74eaa8be7221: Already exists
	2d6e98fe4040: Already exists
	452c06dec5fa: Already exists
	7b3c215894de: Already exists
	094529398b79: Already exists
	449fe646e95b: Already exists
	3d7b5d01f511: Pull complete
	5254fd4c872b: Pull complete
	fc9d6d10bf6f: Pull complete
	4b57bd4bf4f4: Pull complete
	Digest: sha256:d0905533a2883771f864144cb5b4cf20323656878bdc32e85e4c4c1c18587bb0
	Status: Downloaded newer image for dojot/flowbroker:0.3.0-nightly20180416
```
After killing the flowbroker as you said to, i've tried to get the flowbroker up again, but got this 
```javascript
flowbroker_1            | [executor] initializing ...
flowbroker_1            | [kafka] Producer ready
flowbroker_1            | [kafka] Producer ready
flowbroker_1            | [kafka] Producer ready
flowbroker_1            | [kafka] Producer ready
flowbroker_1            | [api] Service listening on port 80
flowbroker_1            | [kafka] Created consumer (iotagent-5775)[dojot.tenancy : e7251a79-6e4c-48b0-ba28-51d9c9986633]
flowbroker_1            | [ingestor] Tenancy context management initialized
flowbroker_1            | [kafka] Created consumer (iotagent-5775)[device-data : da10c123-1b8c-45f1-9916-02b4dd89b913]
flowbroker_1            | [amqp] producer ready ... 
flowbroker_1            | [amqp] producer ready ... 
flowbroker_1            | [executor] Worker ready.
flowbroker_1            | [amqp] consumer ready ... 
flowbroker_1            | events.js:183
flowbroker_1            |       throw er; // Unhandled 'error' event
flowbroker_1            |       ^
flowbroker_1            | 
flowbroker_1            | TypeError: Cannot read property 'type' of undefined
flowbroker_1            |     at Executor.hop (/opt/flowbroker/orchestrator/executor.js:38:51)
flowbroker_1            |     at channel.consume (/opt/flowbroker/orchestrator/amqp.js:104:9)
flowbroker_1            |     at Channel.BaseChannel.dispatchMessage (/opt/flowbroker/orchestrator/node_modules/amqplib/lib/channel.js:466:12)
flowbroker_1            |     at Channel.BaseChannel.handleDelivery (/opt/flowbroker/orchestrator/node_modules/amqplib/lib/channel.js:475:15)
flowbroker_1            |     at emitOne (events.js:116:13)
flowbroker_1            |     at Channel.emit (events.js:211:7)
flowbroker_1            |     at /opt/flowbroker/orchestrator/node_modules/amqplib/lib/channel.js:263:10
flowbroker_1            |     at Channel.content [as handleMessage] (/opt/flowbroker/orchestrator/node_modules/amqplib/lib/channel.js:316:9)
flowbroker_1            |     at Channel.C.acceptMessageFrame (/opt/flowbroker/orchestrator/node_modules/amqplib/lib/channel.js:231:31)
flowbroker_1            |     at Channel.C.accept (/opt/flowbroker/orchestrator/node_modules/amqplib/lib/channel.js:384:17)
flowbroker_1            |     at Connection.mainAccept [as accept] (/opt/flowbroker/orchestrator/node_modules/amqplib/lib/connection.js:64:33)
flowbroker_1            |     at Socket.go (/opt/flowbroker/orchestrator/node_modules/amqplib/lib/connection.js:477:48)
flowbroker_1            |     at emitNone (events.js:106:13)
flowbroker_1            |     at Socket.emit (events.js:208:7)
flowbroker_1            |     at emitReadable_ (_stream_readable.js:513:10)
flowbroker_1            |     at emitReadable (_stream_readable.js:507:7)
dockercompose_flowbroker_1 exited with code 1
```
So i had to get docker-compose down. After getting docker-compose up again and created new template, new device and new data flows (email and http request) and got this logs when my device tried to send something (the logs was capture running `docker-compose logs --tail=0 --follow`).

```javascript
iotagent-mqtt_1         | will handle authentication request undefined undefined mosqpub/8377-lucas
iotagent-mqtt_1         | ignoring internal message $SYS/LVC~ni2/new/clients undefined
iotagent-mqtt_1         | will attempt to use client.id as id source
iotagent-mqtt_1         | will attempt to use topic as id source
iotagent-mqtt_1         | ignoring internal message $SYS/LVC~ni2/disconnect/clients undefined
device-manager_1        | 172.18.0.21 - - [18/Apr/2018:17:41:05 +0000] "GET /device/83f668 HTTP/1.1" 200 1412 "-" "axios/0.17.1"
iotagent-mqtt_1         | Published /admin/83f668/attrs { current: 0,
iotagent-mqtt_1         |   temperature: 31.964783,
iotagent-mqtt_1         |   apparent_power: 16.590271,
iotagent-mqtt_1         |   power_factor: 0.946289,
iotagent-mqtt_1         |   voltage: 127.492249,
iotagent-mqtt_1         |   active_power: 15.699707,
iotagent-mqtt_1         |   power_frequency: 60.071228,
iotagent-mqtt_1         |   reactive_power: 0,
iotagent-mqtt_1         |   teste: 10 } mosqpub/8377-lucas undefined undefined
data-broker_1           | will initialize ingestion handler: device-data 857c49d5-fca9-42d2-95be-54ff15a7d8dd
data-broker_1           | ::ffff:172.18.0.21 - GET /topic/device-data HTTP/1.1 200 48 - 2.086 ms
data-broker_1           | will publish event [admin] {"metadata":{"deviceid":"83f668","tenant":"admin","timestamp":1524073265056,"templates":[1]},"attrs":{"current":0,"temperature":31.964783,"apparent_power":16.590271,"power_factor":0.946289,"voltage":127.492249,"active_power":15.699707,"power_frequency":60.071228,"reactive_power":0,"teste":10}}
mongodb_1               | 2018-04-18T17:41:05.073+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.20:57752 #8 (8 connections now open)
flowbroker_1            | [ingestor] got new device event: { metadata: 
flowbroker_1            |    { deviceid: '83f668',
flowbroker_1            |      tenant: 'admin',
flowbroker_1            |      timestamp: 1524073265056,
flowbroker_1            |      templates: [ 1 ] },
flowbroker_1            |   attrs: 
flowbroker_1            |    { current: 0,
flowbroker_1            |      temperature: 31.964783,
flowbroker_1            |      apparent_power: 16.590271,
flowbroker_1            |      power_factor: 0.946289,
flowbroker_1            |      voltage: 127.492249,
flowbroker_1            |      active_power: 15.699707,
flowbroker_1            |      power_frequency: 60.071228,
flowbroker_1            |      reactive_power: 0,
flowbroker_1            |      teste: 10 } }
mongodb_1               | 2018-04-18T17:41:05.074+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.20:57754 #9 (9 connections now open)
data-broker_1           | will publish event [admin] {"metadata": {"deviceid": "83f668", "tenant": "admin", "status": "online", "reason": "statusUpdate"}, "attrs": {"status": "online"}}
mongodb_1               | 2018-04-18T17:41:05.080+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.24:45720 #10 (10 connections now open)
flowbroker_1            | [ingestor] got new device event: { metadata: 
flowbroker_1            |    { deviceid: '83f668',
flowbroker_1            |      tenant: 'admin',
flowbroker_1            |      status: 'online',
flowbroker_1            |      reason: 'statusUpdate' },
flowbroker_1            |   attrs: { status: 'online' } }
mongodb_1               | 2018-04-18T17:41:05.089+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.24:45722 #11 (11 connections now open)
flowbroker_1            | events.js:183
flowbroker_1            |       throw er; // Unhandled 'error' event
flowbroker_1            |       ^
flowbroker_1            | 
flowbroker_1            | TypeError: Cannot read property 'type' of undefined
flowbroker_1            |     at Executor.hop (/opt/flowbroker/orchestrator/executor.js:38:51)
flowbroker_1            |     at channel.consume (/opt/flowbroker/orchestrator/amqp.js:104:9)
flowbroker_1            |     at Channel.BaseChannel.dispatchMessage (/opt/flowbroker/orchestrator/node_modules/amqplib/lib/channel.js:466:12)
flowbroker_1            |     at Channel.BaseChannel.handleDelivery (/opt/flowbroker/orchestrator/node_modules/amqplib/lib/channel.js:475:15)
flowbroker_1            |     at emitOne (events.js:116:13)
flowbroker_1            |     at Channel.emit (events.js:211:7)
flowbroker_1            |     at /opt/flowbroker/orchestrator/node_modules/amqplib/lib/channel.js:263:10
flowbroker_1            |     at Channel.content [as handleMessage] (/opt/flowbroker/orchestrator/node_modules/amqplib/lib/channel.js:316:9)
flowbroker_1            |     at Channel.C.acceptMessageFrame (/opt/flowbroker/orchestrator/node_modules/amqplib/lib/channel.js:231:31)
flowbroker_1            |     at Channel.C.accept (/opt/flowbroker/orchestrator/node_modules/amqplib/lib/channel.js:384:17)
flowbroker_1            |     at Connection.mainAccept [as accept] (/opt/flowbroker/orchestrator/node_modules/amqplib/lib/connection.js:64:33)
flowbroker_1            |     at Socket.go (/opt/flowbroker/orchestrator/node_modules/amqplib/lib/connection.js:477:48)
flowbroker_1            |     at emitNone (events.js:106:13)
flowbroker_1            |     at Socket.emit (events.js:208:7)
flowbroker_1            |     at emitReadable_ (_stream_readable.js:513:10)
flowbroker_1            |     at emitReadable (_stream_readable.js:507:7)
mongodb_1               | 2018-04-18T17:41:05.143+0000 I NETWORK  [conn10] end connection 172.18.0.24:45720 (10 connections now open)
mongodb_1               | 2018-04-18T17:41:05.143+0000 I NETWORK  [conn5] end connection 172.18.0.24:45272 (10 connections now open)
mongodb_1               | 2018-04-18T17:41:05.143+0000 I NETWORK  [conn11] end connection 172.18.0.24:45722 (10 connections now open)
rabbitmq_1              | 2018-04-18 17:41:05.143 [warning] <0.521.0> closing AMQP connection <0.521.0> (172.18.0.24:51668 -> 172.18.0.10:5672, vhost: '/', user: 'guest'):
rabbitmq_1              | client unexpectedly closed TCP connection
rabbitmq_1              | 2018-04-18 17:41:05.143 [warning] <0.496.0> closing AMQP connection <0.496.0> (172.18.0.24:51664 -> 172.18.0.10:5672, vhost: '/', user: 'guest'):
rabbitmq_1              | client unexpectedly closed TCP connection
rabbitmq_1              | 2018-04-18 17:41:05.143 [warning] <0.493.0> closing AMQP connection <0.493.0> (172.18.0.24:51660 -> 172.18.0.10:5672, vhost: '/', user: 'guest'):
rabbitmq_1              | client unexpectedly closed TCP connection
docker-monitor_1        | 2018-04-18 17:41:05,156 - docker-monitor.alarms - INFO - Sending alarm: {"namespace": "dojot.docker", "domain": "ContainerError", "primarySubject": {"container": "dockercompose_flowbroker_1", "image": "dojot/flowbroker:0.3.0-nightly20180416"}, "additionalData": {"exitCode": "1", "imageId": "sha256:cfe20d3344ce72324faa9ce49b6f703943eaf569466ff233a72dbd431b8e6bb8"}, "severity": "Major", "eventTimestamp": "2018-04-18T17:41:05"}
alarm-manager_1         | 17:41:05,159 INFO  [com.cpqd.vppd.alarmmanager.alarmreceiver.AlarmHandler] (EJB default - 7) validateAlarm
docker-monitor_1        | 2018-04-18 17:41:05,846 - docker-monitor.alarms - INFO - Sending alarm: {"namespace": "dojot.docker", "domain": "ContainerError", "primarySubject": {"container": "dockercompose_flowbroker_1", "image": "dojot/flowbroker:0.3.0-nightly20180416"}, "additionalData": {"exitCode": "NA", "imageId": "sha256:cfe20d3344ce72324faa9ce49b6f703943eaf569466ff233a72dbd431b8e6bb8"}, "severity": "Clear", "eventTimestamp": "2018-04-18T17:41:05"}
alarm-manager_1         | 17:41:05,848 INFO  [com.cpqd.vppd.alarmmanager.alarmreceiver.AlarmHandler] (EJB default - 8) validateAlarm
mongodb_1               | 2018-04-18T17:41:06.272+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.22:42064 #12 (9 connections now open)
rabbitmq_1              | 2018-04-18 17:41:06.275 [info] <0.554.0> accepting AMQP connection <0.554.0> (172.18.0.22:36498 -> 172.18.0.10:5672)
rabbitmq_1              | 2018-04-18 17:41:06.308 [info] <0.557.0> accepting AMQP connection <0.557.0> (172.18.0.22:36502 -> 172.18.0.10:5672)
data-broker_1           | ::ffff:172.18.0.22 - GET /topic/dojot.tenancy?global=true HTTP/1.1 200 48 - 2.215 ms
kafka_1                 | [2018-04-18 17:41:06,325] INFO [GroupCoordinator 0]: Preparing to restabilize group iotagent-3543 with old generation 0 (kafka.coordinator.GroupCoordinator)
kafka_1                 | [2018-04-18 17:41:06,326] INFO [GroupCoordinator 0]: Stabilized group iotagent-3543 generation 1 (kafka.coordinator.GroupCoordinator)
kafka_1                 | [2018-04-18 17:41:06,334] INFO [GroupCoordinator 0]: Assignment received from leader for group iotagent-3543 for generation 1 (kafka.coordinator.GroupCoordinator)
auth_1                  | 172.18.0.22 - - [18/Apr/2018:17:41:06 +0000] "GET /admin/tenants HTTP/1.1" 200 22 "-" "axios/0.18.0"
data-broker_1           | will initialize ingestion handler: device-data 857c49d5-fca9-42d2-95be-54ff15a7d8dd
data-broker_1           | ::ffff:172.18.0.22 - GET /topic/device-data HTTP/1.1 200 48 - 1.044 ms
rabbitmq_1              | 2018-04-18 17:41:06.353 [info] <0.557.0> connection <0.557.0> (172.18.0.22:36502 -> 172.18.0.10:5672): user 'guest' authenticated and granted access to vhost '/'
rabbitmq_1              | 2018-04-18 17:41:06.353 [info] <0.554.0> connection <0.554.0> (172.18.0.22:36498 -> 172.18.0.10:5672): user 'guest' authenticated and granted access to vhost '/'
kafka_1                 | [2018-04-18 17:41:06,360] INFO [GroupCoordinator 0]: Preparing to restabilize group iotagent-3543 with old generation 1 (kafka.coordinator.GroupCoordinator)
rabbitmq_1              | 2018-04-18 17:41:06.361 [info] <0.578.0> accepting AMQP connection <0.578.0> (172.18.0.22:36520 -> 172.18.0.10:5672)
rabbitmq_1              | 2018-04-18 17:41:06.407 [info] <0.578.0> connection <0.578.0> (172.18.0.22:36520 -> 172.18.0.10:5672): user 'guest' authenticated and granted access to vhost '/'
mongodb_1               | 2018-04-18T17:41:06.474+0000 I NETWORK  [conn12] end connection 172.18.0.22:42064 (8 connections now open)
rabbitmq_1              | 2018-04-18 17:41:06.475 [warning] <0.578.0> closing AMQP connection <0.578.0> (172.18.0.22:36520 -> 172.18.0.10:5672, vhost: '/', user: 'guest'):
rabbitmq_1              | client unexpectedly closed TCP connection
rabbitmq_1              | 2018-04-18 17:41:06.475 [warning] <0.557.0> closing AMQP connection <0.557.0> (172.18.0.22:36502 -> 172.18.0.10:5672, vhost: '/', user: 'guest'):
rabbitmq_1              | client unexpectedly closed TCP connection
rabbitmq_1              | 2018-04-18 17:41:06.475 [warning] <0.554.0> closing AMQP connection <0.554.0> (172.18.0.22:36498 -> 172.18.0.10:5672, vhost: '/', user: 'guest'):
rabbitmq_1              | client unexpectedly closed TCP connection
docker-monitor_1        | 2018-04-18 17:41:06,484 - docker-monitor.alarms - INFO - Sending alarm: {"namespace": "dojot.docker", "domain": "ContainerError", "primarySubject": {"container": "dockercompose_flowbroker_1", "image": "dojot/flowbroker:0.3.0-nightly20180416"}, "additionalData": {"exitCode": "1", "imageId": "sha256:cfe20d3344ce72324faa9ce49b6f703943eaf569466ff233a72dbd431b8e6bb8"}, "severity": "Major", "eventTimestamp": "2018-04-18T17:41:06"}
alarm-manager_1         | 17:41:06,486 INFO  [com.cpqd.vppd.alarmmanager.alarmreceiver.AlarmHandler] (EJB default - 9) validateAlarm
dockercompose_flowbroker_1 exited with code 1
docker-monitor_1        | 2018-04-18 17:41:07,200 - docker-monitor.alarms - INFO - Sending alarm: {"namespace": "dojot.docker", "domain": "ContainerError", "primarySubject": {"container": "dockercompose_flowbroker_1", "image": "dojot/flowbroker:0.3.0-nightly20180416"}, "additionalData": {"exitCode": "NA", "imageId": "sha256:cfe20d3344ce72324faa9ce49b6f703943eaf569466ff233a72dbd431b8e6bb8"}, "severity": "Clear", "eventTimestamp": "2018-04-18T17:41:07"}
alarm-manager_1         | 17:41:07,203 INFO  [com.cpqd.vppd.alarmmanager.alarmreceiver.AlarmHandler] (EJB default - 10) validateAlarm
flowbroker_1            | [executor] initializing ...
mongodb_1               | 2018-04-18T17:41:07.653+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.22:42100 #13 (9 connections now open)
rabbitmq_1              | 2018-04-18 17:41:07.657 [info] <0.599.0> accepting AMQP connection <0.599.0> (172.18.0.22:36534 -> 172.18.0.10:5672)
```

**Comment by giovannicuriel** [comment]
Just a few questions for clarifications on our side: 

- Are you using the web interface to create this flow or are you sending the flow creation request by hand?
- Can you post the flow description? You can, of course, omit your e-mail and server configuration - what we need is the flow JSON data. To do that, you can use the developer tools in your browser (accessed via F12 in Chrome or CRTL+Shift+C in Firefox. Internet Explorer / Edge and Safari also have these tools) and capture the data on the network tab related to the POST HTTP request when you save the flow.

We are currently improving the error handling of flowbuilder, so that this kind of problem won't kill the container (at least).

**Comment by klossteles** [comment]
- I am creating those flows using the web interface

- These are the jsons generate after saving the flows:
**Email flow**
```json
{
   "message":"ok",
   "flow":{
      "name":"email_flow",
      "enabled":true,
      "id":"667d5e14-025a-4bae-b20e-313bb5eb76c2",
      "flow":[
         {
            "id":"3c6ce20a.c331de",
            "type":"tab",
            "label":"Flow 1"
         },
         {
            "id":"9e1616e7.c80588",
            "type":"template",
            "z":"3c6ce20a.c331de",
            "name":"template",
            "field":"emailBody",
            "fieldType":"msg",
            "format":"handlebars",
            "syntax":"mustache",
            "template":"Your device generate this: {{payload}} !",
            "output":"str",
            "x":381.5,
            "y":176,
            "wires":[
               [
                  "84a1ca8.a44c838"
               ]
            ]
         },
         {
            "id":"84a1ca8.a44c838",
            "type":"email",
            "z":"3c6ce20a.c331de",
            "server":"smtp.gmail.com",
            "port":"465",
            "secure":true,
            "name":"admin",
            "dname":"email",
            "to":"REMOVED_CONFIGURATION",
            "from":"REMOVED_CONFIGURATION",
            "subject":"Email sent by device",
            "body":"emailBody",
            "userid":"admin",
            "password":"admin",
            "x":559.5,
            "y":242,
            "wires":[

            ]
         },
         {
            "id":"f196d372.891cd",
            "type":"device in",
            "z":"3c6ce20a.c331de",
            "name":"input device",
            "device":"{\"id\":\"d63ed3\"}",
            "status":"true",
            "_device_id":"d63ed3",
            "_device_label":"",
            "_device_type":"",
            "x":204.5,
            "y":103,
            "wires":[
               [
                  "9e1616e7.c80588"
               ]
            ]
         }
      ],
      "created":1524080514532,
      "updated":1524081367243
   }
}
```

![emailflow](https://user-images.githubusercontent.com/28739434/38955429-0d489364-432b-11e8-845f-4a4421017d91.png)



**Request flow** 
```json
{
   "message":"ok",
   "flow":{
      "name":"server_flow",
      "enabled":true,
      "id":"e5381480-4782-4ff1-8def-fba133516a9b",
      "flow":[
         {
            "id":"8b63f794.763678",
            "type":"tab",
            "label":"Flow 1"
         },
         {
            "id":"fdc745a6.6a5c58",
            "type":"template",
            "z":"8b63f794.763678",
            "name":"template_server",
            "field":"payload",
            "fieldType":"msg",
            "format":"handlebars",
            "syntax":"mustache",
            "template":"This is the payload: {{payload}} !",
            "output":"str",
            "x":414.5,
            "y":197,
            "wires":[
               [
                  "8891e7ee.c2dea8"
               ]
            ]
         },
         {
            "id":"8891e7ee.c2dea8",
            "type":"http",
            "z":"8b63f794.763678",
            "name":"server_connection",
            "method":"POST",
            "ret":"txt",
            "body":"payload",
            "url":"REMOVED_CONFIGURATION",
            "x":639.5,
            "y":253,
            "wires":[

            ]
         },
         {
            "id":"923d78da.7bd938",
            "type":"device in",
            "z":"8b63f794.763678",
            "name":"",
            "device":"{\"id\":\"d63ed3\"}",
            "status":"true",
            "_device_id":"d63ed3",
            "_device_label":"",
            "_device_type":"",
            "x":84.5,
            "y":70,
            "wires":[
               [
                  "a640b590.b18898"
               ]
            ]
         },
         {
            "id":"a640b590.b18898",
            "type":"switch",
            "z":"8b63f794.763678",
            "name":"",
            "property":"payload",
            "propertyType":"msg",
            "rules":[
               {
                  "t":"gt",
                  "v":"100",
                  "vt":"num"
               }
            ],
            "checkall":"true",
            "outputs":1,
            "x":216.5,
            "y":140,
            "wires":[
               [
                  "fdc745a6.6a5c58"
               ]
            ]
         }
      ],
      "created":1524080514550,
      "updated":1524081776452
   }
}
```

![requestflow](https://user-images.githubusercontent.com/28739434/38955439-12c6da58-432b-11e8-97f2-6857f4592f05.png)

**Comment by klossteles** [comment]
Hi
Was there any solution for this problem? 
After the uncomments http node, i've updated dojot from master branch but still cannot send a request through http node.
I am  keep getting this log from `sudo docker-compose logs --tail=0 --follow`  

```javascript 
Attaching to docker-compose_kong-config_1, docker-compose_iotagent-mqtt_1, docker-compose_flowbroker_1, docker-compose_persister_1, docker-compose_apigw_1, docker-compose_kong-migration_1, docker-compose_auth_1, docker-compose_device-manager_1, docker-compose_data-broker_1, docker-compose_kafka_1, docker-compose_history_1, docker-compose_zookeeper_1, docker-compose_mosca-redis_1, docker-compose_mongodb_1, docker-compose_auth-redis_1, docker-compose_postgres_1, docker-compose_ejbca_1, docker-compose_device-manager-redis_1, docker-compose_rabbitmq_1, docker-compose_gui_1, docker-compose_data-broker-redis_1
docker-compose_kong-config_1 exited with code 0
docker-compose_kong-migration_1 exited with code 0
iotagent-mqtt_1         | will handle authentication request undefined undefined mosqpub/31196-joaquim-v
iotagent-mqtt_1         | ignoring internal message $SYS/jt4B9AA/new/clients undefined
iotagent-mqtt_1         | will attempt to use client.id as id source
iotagent-mqtt_1         | will attempt to use topic as id source
iotagent-mqtt_1         | ignoring internal message $SYS/jt4B9AA/disconnect/clients undefined
device-manager_1        | INFO     | [24/07/2018:17:53:31] |DeviceManager.DeviceHandler| Getting the device with id b5d225.
iotagent-mqtt_1         | Published /admin/b5d225/attrs { current: 0,
iotagent-mqtt_1         |   temperature: 31.964783,
iotagent-mqtt_1         |   apparent_power: 16.590271,
iotagent-mqtt_1         |   power_factor: 0.946289,
iotagent-mqtt_1         |   voltage: 127.492249,
iotagent-mqtt_1         |   power_frequency: 60.071228,
iotagent-mqtt_1         |   reactive_power: 0,
iotagent-mqtt_1         |   active_power: 127.49222,
iotagent-mqtt_1         |   teste: 5 } mosqpub/31196-joaquim-v undefined undefined
data-broker_1           | debug: Processing message just received...
device-manager_1        | DEBUG    | [24/07/2018:17:53:31] |DeviceManager.StatusMonitor| Got kafka event [dada465e-097c-48e6-8eb4-60c992572c7b] ConsumerRecord(topic='dada465e-097c-48e6-8eb4-60c992572c7b', partition=0, offset=56, timestamp=1532521639122, timestamp_type=0, key=None, value=b'{"metadata":{"deviceid":"b5d225","tenant":"admin","timestamp":1532521639122,"templates":[1]},"attrs":{"current":0,"temperature":31.964783,"apparent_power":16.590271,"power_factor":0.946289,"voltage":127.492249,"power_frequency":60.071228,"reactive_power":0,"active_power":127.49222,"teste":5}}', checksum=73491069, serialized_key_size=-1, serialized_value_size=293)
flowbroker_1            | [ingestor] got new device event: { metadata: 
data-broker_1           | debug: Trying to parse received message payload...
flowbroker_1            |    { deviceid: 'b5d225',
flowbroker_1            |      tenant: 'admin',
flowbroker_1            |      timestamp: 1532521639122,
flowbroker_1            |      templates: [ 1 ] },
flowbroker_1            |   attrs: 
flowbroker_1            |    { current: 0,
flowbroker_1            |      temperature: 31.964783,
flowbroker_1            |      apparent_power: 16.590271,
flowbroker_1            |      power_factor: 0.946289,
flowbroker_1            |      voltage: 127.492249,
flowbroker_1            |      power_frequency: 60.071228,
flowbroker_1            |      reactive_power: 0,
flowbroker_1            |      active_power: 127.49222,
flowbroker_1            |      teste: 5 } }
data-broker_1           | debug: ... message payload was successfully parsed.
data-broker_1           | debug: Will publish event to namespace admin: {"metadata":{"deviceid":"b5d225","tenant":"admin","timestamp":1532521639122,"templates":[1]},"attrs":{"current":0,"temperature":31.964783,"apparent_power":16.590271,"power_factor":0.946289,"voltage":127.492249,"power_frequency":60.071228,"reactive_power":0,"active_power":127.49222,"teste":5}}
flowbroker_1            | debug: Executing switch node...
flowbroker_1            | debug: ... switch node was successfully executed.
flowbroker_1            | [executor] will handle node switch
flowbroker_1            | [executor] hop (switch) result: [null,{"payload":{"current":0,"temperature":31.964783,"apparent_power":16.590271,"power_factor":0.946289,"voltage":127.492249,"power_frequency":60.071228,"reactive_power":0,"active_power":127.49222,"teste":5}}]
data-broker_1           | debug: ... received message was successfully processed.
flowbroker_1            | [executor] will handle node change
flowbroker_1            | debug: Executing change node...
flowbroker_1            | debug: ... change node was successfully executed.
flowbroker_1            | [executor] hop (change) result: [{"payload":"OK"}]
flowbroker_1            | [executor] will handle node http
flowbroker_1            | debug: Executing http node...
flowbroker_1            | debug: HTTP request about to be sent: [object Object]
flowbroker_1            | Got invalid request: user is not defined in token:  undefined
device-manager_1        | INFO     | [24/07/2018:17:53:31] |DeviceManager.StatusMonitor| will set admin:b5d225 online for 5s
flowbroker_1            | debug: ... http node was successfully executed.
flowbroker_1            | [executor] hop (http) result: [{"payload":"{\"message\":\"Authentication (JWT) required for API\"}","statusCode":401,"headers":{"x-powered-by":"Express","content-type":"application/json; charset=utf-8","content-length":"51","etag":"W/\"33-ZkSDNTVQEd1PS7r41UEHv7U+hX8\"","date":"Wed, 25 Jul 2018 12:27:19 GMT","connection":"close"},"responseUrl":"http://localhost/guia/contrel/dojot"}]
data-broker_1           | debug: Processing message just received...
flowbroker_1            | [ingestor] got new device event: { metadata: 
flowbroker_1            |    { deviceid: 'b5d225',
flowbroker_1            |      tenant: 'admin',
flowbroker_1            |      status: 'online',
flowbroker_1            |      reason: 'statusUpdate' } }
device-manager_1        | DEBUG    | [24/07/2018:17:53:31] |DeviceManager.StatusMonitor| Got kafka event [dada465e-097c-48e6-8eb4-60c992572c7b] ConsumerRecord(topic='dada465e-097c-48e6-8eb4-60c992572c7b', partition=0, offset=57, timestamp=1532521639136, timestamp_type=0, key=None, value=b'{"metadata": {"deviceid": "b5d225", "tenant": "admin", "status": "online", "reason": "statusUpdate"}}', checksum=2745842340, serialized_key_size=-1, serialized_value_size=101)
data-broker_1           | debug: Trying to parse received message payload...
data-broker_1           | debug: ... message payload was successfully parsed.
data-broker_1           | debug: Will publish event to namespace admin: {"metadata": {"deviceid": "b5d225", "tenant": "admin", "status": "online", "reason": "statusUpdate"}}
data-broker_1           | debug: ... received message was successfully processed.
device-manager_1        | DEBUG    | [24/07/2018:17:53:31] |DeviceManager.StatusMonitor| scan st:admin:*:0:exp 0 [b'st:admin:b5d225:0:exp']
device-manager_1        | DEBUG    | [24/07/2018:17:53:31] |DeviceManager.StatusMonitor| gc devices ['st:admin:b5d225:0:exp']
device-manager_1        | DEBUG    | [24/07/2018:17:53:31] |DeviceManager.StatusMonitor| will check st:admin:b5d225:0:exp 1532521644.1369326
device-manager_1        | DEBUG    | [24/07/2018:17:53:31] |DeviceManager.StatusMonitor| scan st:admin:*:0:exp 0 [b'st:admin:b5d225:0:exp']
device-manager_1        | DEBUG    | [24/07/2018:17:53:31] |DeviceManager.StatusMonitor| gc devices ['st:admin:b5d225:0:exp']
device-manager_1        | DEBUG    | [24/07/2018:17:53:31] |DeviceManager.StatusMonitor| will check st:admin:b5d225:0:exp 1532521644.1369326
device-manager_1        | DEBUG    | [24/07/2018:17:53:31] |DeviceManager.StatusMonitor| scan st:admin:*:0:exp 0 [b'st:admin:b5d225:0:exp']
device-manager_1        | DEBUG    | [24/07/2018:17:53:31] |DeviceManager.StatusMonitor| gc devices ['st:admin:b5d225:0:exp']
device-manager_1        | DEBUG    | [24/07/2018:17:53:31] |DeviceManager.StatusMonitor| will check st:admin:b5d225:0:exp 1532521644.1369326
device-manager_1        | DEBUG    | [24/07/2018:17:53:31] |DeviceManager.StatusMonitor| device st:admin:b5d225:0:exp offline
flowbroker_1            | [ingestor] got new device event: { metadata: 
flowbroker_1            |    { deviceid: 'b5d225',
flowbroker_1            |      tenant: 'admin',
flowbroker_1            |      status: 'offline',
flowbroker_1            |      reason: 'statusUpdate' } }
data-broker_1           | debug: Processing message just received...
data-broker_1           | debug: Trying to parse received message payload...
data-broker_1           | debug: ... message payload was successfully parsed.
data-broker_1           | debug: Will publish event to namespace admin: {"metadata": {"deviceid": "b5d225", "tenant": "admin", "status": "offline", "reason": "statusUpdate"}}
data-broker_1           | debug: ... received message was successfully processed.
device-manager_1        | DEBUG    | [24/07/2018:17:53:31] |DeviceManager.StatusMonitor| Got kafka event [dada465e-097c-48e6-8eb4-60c992572c7b] ConsumerRecord(topic='dada465e-097c-48e6-8eb4-60c992572c7b', partition=0, offset=58, timestamp=1532521644285, timestamp_type=0, key=None, value=b'{"metadata": {"deviceid": "b5d225", "tenant": "admin", "status": "offline", "reason": "statusUpdate"}}', checksum=2263932923, serialized_key_size=-1, serialized_value_size=102)
```

The only change that i've to my flow was adding two change nodes.

**Comment by giovannicuriel** [comment]
Hi!

The HTTP node is returning an error:
```
flowbroker_1            | debug: HTTP request about to be sent: [object Object]
flowbroker_1            | Got invalid request: user is not defined in token:  undefined
flowbroker_1            | debug: ... http node was successfully executed.
flowbroker_1            | [executor] hop (http) result: [{"payload":"{\"message\":\"Authentication (JWT) required for API\"}","statusCode":401,"headers":{"x-powered-by":"Express","content-type":"application/json; charset=utf-8","content-length":"51","etag":"W/\"33-ZkSDNTVQEd1PS7r41UEHv7U+hX8\"","date":"Wed, 25 Jul 2018 12:27:19 GMT","connection":"close"},"responseUrl":"http://localhost/guia/contrel/dojot"}
```

Apparently, the token used to send the request is not being recognized in the other end. Could you check this?

(BTW, we are brainstorming ways to debug node errors like this. If you have any suggestions, please, let us know :smile:)

**Comment by giovannicuriel** [comment]
Another thing: you can set the headers of a HTTP request by setting a `headers` property in a `change` node, such as:

![image](https://user-images.githubusercontent.com/6285982/43204391-107ca520-8ff7-11e8-96ae-7a7e27f279fa.png)

We will update the documentation to indicate this.

**Comment by klossteles** [comment]
Using this way finally worked. 
Thanks for help guys.
